#!/usr/bin/with-contenv bash
# shellcheck shell=bash

folders=(
    /app/raneto/node_modules/@raneto/theme-default/dist/public/images
    /app/raneto/content
)

for i in "${folders[@]}"; do
    if [[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]]; then
        rm -Rf "$i" && \
        ln -s /config/"$(basename "$i")" "$i"
    fi

    if [[ -e "$i" && ! -L "$i" ]]; then
        mv "$i" /config/"$(basename "$i")" && \
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

# create local user server files
if [[ ! -f /config/config.default.js ]]; then
    cp /defaults/config.default.js /config/config.default.js
fi

if [[ ! -f /app/raneto/server.js ]]; then
    cp /defaults/server.js /app/raneto/server.js
fi

# permissions
lsiown -R abc:abc \
    /config 
